[package]
name = "compugenesis"
version = "0.1.0"
authors = ["pimpale <gpimpale29@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
rand = "0.8.5"
vulkano = "0.29.0"
vulkano-shaders = "0.29.0"
vulkano-win = "0.29.0"
cgmath = "0.18.0"
image = "0.24.2"
winit = "0.26.1"
time = "0.3.9"
csv = "1.1.6"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
bytemuck = "1.9.1"
